spring.application.name=WebWorks-Backend
debug=false

spring.config.import=optional:file:.env[.properties],optional:file:./.env[.properties]

#acceso a base de datos
# Base principal
spring.datasource.first.jdbc-url=${SPRING_DATASOURCE_FIRST_URL}
spring.datasource.first.username=${SPRING_DATASOURCE_FIRST_USERNAME}
spring.datasource.first.password=${SPRING_DATASOURCE_FIRST_PASSWORD}
spring.datasource.first.driver-class-name=org.postgresql.Driver
spring.datasource.first.jpa.hibernate.ddl-auto=update
spring.datasource.first.jpa.show-sql=false


# JWT
app.security.jwt.issuer=webworks-backend
app.security.jwt.access-secret=${APP_SECURITY_JWT_ACCESS_SECRET}
app.security.jwt.api-secret=${APP_SECURITY_JWT_API_SECRET}

# CORS (Angular)
app.security.cors.allowed-origins=${APP_SECURITY_CORS_ALLOWED_ORIGINS}

# Cookie JWT
app.security.cookie.access.name=access_token
app.security.cookie.api.name=api_token
app.security.cookie.api.path=/
app.security.cookie.secure=false
app.security.cookie.same-site=Lax

# JWT TTL
app.security.jwt.access-token-validity-ms=900000
app.security.jwt.api-token-validity-ms=604800000

server.port= ${PORT}
server.servlet.context-path=${CONTEXT_PATH:}



# Upload de archivos
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=12MB

server.tomcat.max-http-form-post-size=12MB
media.location=mediafiles


# security
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
